name: Events demo
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output events
        run: echo "${{toJson(github.event)}}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test  code
        run: npm run test
      - name: Build code
        run: npm run build
