name: Deploy to cPanel via FTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build React Vite App
      - name: Install frontend dependencies
        run: npm install
        # working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        # working-directory: ./frontend

      # Deploy Frontend (dist/) via FTP
      - name: FTP Deploy Frontend
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./dist/
          server-dir: ./public_html/eazworld/
      - name: Verify Deployment
        run: |
          echo "Deployed files:"
          curl -s https://eazworld/public_html/ | grep "Your App Name"

      # Deploy Backend (Express.js) via FTP
      # - name: FTP Deploy Backend
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.0
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./backend/
      #     server-dir: ./yourapp-backend/
