name: Deploy to cPanel via FTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build step
      - name: Build React App
        run: |
          npm install
          npm run build
          echo "Build contents:"
          ls -la ./dist/

      # FTP Deployment with enhanced logging
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./dist/
          server-dir: /home2/eazworld/public_html/
          exclude: |
            **/.env
            **/*.map
          verbose: true
          security: strict

      # Verification step (no lftp required)
      - name: Verify Deployment
        run: |
          echo "Checking uploaded files via curl..."
          curl -I https://yourdomain.com/ | grep "200 OK" || echo "Files not accessible"
