name: Deploy to cPanel via FTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build React Vite App
      - name: Install frontend dependencies
        run: npm install
        # working-directory: ./frontend

      - name: Build frontend
        run: npm run build
      - name: Check dist/ contents
        run: ls -la ./dist/
        # working-directory: ./frontend

      # Deploy Frontend (dist/) via FTP
      - name: FTP Deploy Frontend
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /home2/eazworld/public_html/ # Verified exact path
          protocol: ftp
          exclude: |
            **/.env
            **/*.map
          dangerous-clean-slate: false
      - name: Verify Build Output
        run: ls -la ./dist
      - name: Debug FTP Deployment
        run: |
          echo "Local files to deploy:"
          ls -la ./dist/
          echo "Attempting to list target directory:"
          lftp -e "set ftp:ssl-force true; ls /home2/eazworld/public_html/; quit" \
          -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} \
          ${{ secrets.FTP_SERVER }}
